### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by zim89** [zim89/happy-tails-mantine#65]

**Comment by dimahoncharenko** [comment]
- [ ] Designed 'contact us' form;
- [ ] Validated fields: email, name, content;
- [ ] Implemented support for attaching files to 'content' field;
- [ ] Implemented reading files (for now it's only .txt format);
- [ ] Made post request handler to feedback-controller;
- [ ] Handled error messages under the fields which are positioned absolutely to avoid fields' shifts;
- [ ] When a file is attached, the content field will be ignored.
